// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: scheduler.proto

package server

import (
	"context"

	"scheduler/internal/logic"
	"scheduler/internal/svc"
	"scheduler/pb/scheduler"
)

type SchedulerServer struct {
	svcCtx *svc.ServiceContext
	scheduler.UnimplementedSchedulerServer
}

func NewSchedulerServer(svcCtx *svc.ServiceContext) *SchedulerServer {
	return &SchedulerServer{
		svcCtx: svcCtx,
	}
}

func (s *SchedulerServer) Ping(ctx context.Context, in *scheduler.Request) (*scheduler.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *SchedulerServer) Dispatch(ctx context.Context, in *scheduler.CreateJobRequest) (*scheduler.CreateJobResponse, error) {
	l := logic.NewDispatchLogic(ctx, s.svcCtx)
	return l.Dispatch(in)
}
