// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: scheduler.proto

package schedulerclient

import (
	"context"

	"scheduler/pb/scheduler"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateJobRequest  = scheduler.CreateJobRequest
	CreateJobResponse = scheduler.CreateJobResponse
	Request           = scheduler.Request
	Response          = scheduler.Response

	Scheduler interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		Dispatch(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	}

	defaultScheduler struct {
		cli zrpc.Client
	}
)

func NewScheduler(cli zrpc.Client) Scheduler {
	return &defaultScheduler{
		cli: cli,
	}
}

func (m *defaultScheduler) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := scheduler.NewSchedulerClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultScheduler) Dispatch(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	client := scheduler.NewSchedulerClient(m.cli.Conn())
	return client.Dispatch(ctx, in, opts...)
}
